### ISSUE TITLE
Worldedit related crash with echopet.

### ISSUE THREAD

**Issue by andrewkm** [DSH105/EchoPet#416] opened 2014-10-18 06:58 UTC
Upon issues a //move command we got a complete server crash:

NPE: http://pastie.org/private/fhufhov2vdlpmnzbfbeyg
Crash log: https://gist.github.com/anonymous/1740b5a792f7472744a2

**Comment by DSH105** [comment] 2015-04-09 23:53
Closing - duplicate of #410.

**Closed by DSH105** 2015-04-09 23:53 UTC
