### ISSUE TITLE
Spawn Egg Issues

### ISSUE THREAD

**Issue by SpaZMonKeY777** [DSH105/EchoPet#473] opened 2015-01-02 06:05 UTC
It seems when using the latest development builds of EchoPet on Spigot 1.8, some spawn eggs are throwing errors in console. An example, is trying to use an Ocelot Spawn Egg, it does not consume the egg or spawn the ocelot, and console says "Skipping Entity with id 98".

This error stops occurring when I disable EchoPets, so I imagine it has to be the cause of the issue. Hope it can be fixed, and thanks for your efforts so far on keeping EchoPets updated! :)

**Comment by DSH105** [comment] 2015-01-02 06:31
Closing - duplicate of #462.

**Closed by DSH105** 2015-01-02 06:31 UTC
