### ISSUE TITLE
Pet names losing color value.

### ISSUE THREAD

**Issue by mibby** [DSH105/EchoPet#481] opened 2015-01-19 17:02 UTC
EchoPets dev 32. http://ci.dsh105.com/job/EchoPet-v2/32/

Pet names that have color code values seem to lose color after relogging. As well as lose color when toggling the pet from hiding and showing.

**Comment by DSH105** [comment] 2015-04-09 02:04
Seems like this issue has been around for a while.

Closing this report as a duplicate of #458.

**Closed by DSH105** 2015-04-09 02:04 UTC
Labels: bug
